### PR TITLE
Add less verbose option

### PR DESCRIPTION
**Pull request by nariox**
Inspired by #3. I lack the ability to do it elegantly for just reAddAlias, but I think it might make most sense this way.

I wonder if it would be adequate to set some kind of binary masking, so `reToolsVerbose=3` would include both the total and each of the processed records.

### CODE REVIEW

**Comment by ericonr** [comment]
Using `reToolsVerbose` as a bitmask for enabling verbose output, element count, or any other future option seems like a nice idea.

But I think that would mean you should add macros to identify each flag...

Re. alias, you could try to do it with a lambda capture: `[&count](...) { ...; count++; ...}`

**Comment by nariox** [comment]
I am not well versed with lambda functions, but I am open to it. You could fork and create a PR to my branch if you want.

I did implement a bitmasking option. Let me know what you think of the implementation.

**Comment by brunoseivam** [comment]
LGTM

**Comment by ericonr** [comment]
Thanks! I will try to make it work for alias :)

**Comment by ericonr** [comment]
It had been a while since I last looked at this, so I had lost context.

Having it work for all functions does make the most sense :) so I have nothing to add here.
Thank you very much!

**Pull request merged**
